### ISSUE TITLE
Multi-line macro calls with comments in the middle cause errors

### ISSUE THREAD

**Issue by mkorbel1** [zachjs/sv2v#153]
If a macro is multiple lines, and one of those lines is a comment, it can cause all kinds of errors from sv2v including 'wrong number of arguments' or 'unexpected end of file' type errors.

For example:
```
`MYMACRO(A,
// this is a comment
B)
```

**Comment by zachjs** [comment]
Thank you for finding and reporting this issue! As of 9aa8b7033e71161cb291aa72288c9f3393b3456d, comments are now handled within macro arguments, for both macro definitions and macro invocations. Please let me know if it works for you!

**Comment by mkorbel1** [comment]
Yes, it works!  Thanks!
