### ISSUE TITLE
Handling of // synopsys translate_off/on 

### ISSUE THREAD

**Issue by stitchlibar** [zachjs/sv2v#170]
SV2V seems simply remove //synopsys translate_off/on micros and keep the code between. Is there an option to remove this portion of code after conversion?

**Comment by zachjs** [comment]
For the same reasons mentioned in https://github.com/verilator/verilator/issues/24, sv2v does not (and almost certainly will not) provide any special handling for such vendor-specific comments. I strongly encourage switching to `ifdef`s, which are principled and portable.

**Comment by stitchlibar** [comment]
Thanks. I will try ifdef
