### ISSUE TITLE
wire assignment is removed

### ISSUE THREAD

**Issue by stitchlibar** [zachjs/sv2v#175]
The following module is empty after conversion. SV2V ignores "wire estart = start&enable;". Changing to assign would work.
[test_wireonly.txt](https://github.com/zachjs/sv2v/files/7027711/test_wireonly.txt)

module wiremod #(parameter abc = 1) (/*AUTOARG*/
// Outputs
estart,
// Inputs
enable, start
);
input enable, start;
output estart;
//assign works, wire doesn't
//assign   estart  = start & enable;
wire   estart  = start & enable;
endmodule

**Comment by zachjs** [comment]
sv2v does not yet have good handling for port declarations split in this wag. It may take a few days before I have this properly supported.

**Comment by stitchlibar** [comment]
It is loosely written, if Design Compiler never spoiled the designers by throwing errors in the beginning.
Thanks and take your time.

**Comment by zachjs** [comment]
Yes, those two formulations are equivalent.

**Comment by zachjs** [comment]
Sorry for the delay in getting this issue fixed! It should be fixed in 95c2bc996c2472a749fb23b2521b88ef6e041584. Please let me know if it works for you!

**Comment by stitchlibar** [comment]
Yes, it has been fixed. Great work!
