### ISSUE TITLE
Failure to parse deferred assertion with final 

### ISSUE THREAD

**Issue by saw235** [zachjs/sv2v#177]
The following passes    
```
module xyz();
always_comb begin
        z1: assert final (x == y || z);
end
endmodule
```
but just this fails  
```
module xyz();
        z1: assert final (x == y || z);
endmodule
```
Even though assertions item is part of the module common item, which covers deferred_immediate_assertion_item
Reference : ieee 1800-2017
![image](https://user-images.githubusercontent.com/10379864/132922310-4c11eaf1-8a71-450b-8e22-b6d7191be150.png)
![image](https://user-images.githubusercontent.com/10379864/132922439-fac2e1d1-3f33-45ea-bddc-0569d1f12cce.png)

**Comment by zachjs** [comment]
Thank you for your fix in #178!
