### ISSUE TITLE
conversion error for case with empty default

### ISSUE THREAD

**Issue by tinebp** [zachjs/sv2v#183]
case
  X: value;
  Y: value;
  default: begin assert(false); end
encase

Converts to:

case
  X: value;
  Y: value;
  default:
encase

but should be:

case
  X: value;
  Y: value;
  default:;
encase

**Comment by zachjs** [comment]
I believe this is the same issue and fix as in #184.

**Comment by zachjs** [comment]
Closing for the same reason as in #184: fixed and otherwise inactive.
