### ISSUE TITLE
error eliminating assertions from empty blocks

### ISSUE THREAD

**Issue by tinebp** [zachjs/sv2v#184]
always @(posedge clk) begin
    assert(false);
end

generates

always @(posedge clk)

instead of

always @(posedge clk);

**Comment by zachjs** [comment]
Thank you for reporting this! It looks like this issue is specific to verbose mode. It should be fixed as of 814f96597e457835d7668cdf8fbdba153aa822e2.

**Comment by zachjs** [comment]
Given the inactivity and the availability of a fix, I am closing this issue. Please reopen or file another issue if necessary!
