### ISSUE TITLE
Unable to convert an array of named constants in an enum

### ISSUE THREAD

**Issue by kauser-rl** [zachjs/sv2v#191]
Try to convert a legal SV `typedef enum` below. I'm using `v0.0.9-0-gc822d2e`.

```
package test1_pkg;
   typedef enum logic[8:0] {
     A[2]   = 9'h004,
     B[2]   = 9'h006,
     C[16]  = 9'h0a0,
     D      = 9'h123,
     E[4]   = 9'h124,
     UNUSED = 9'hF00
   } test_t;

endpackage // test1_pkg
```

**Comment by zachjs** [comment]
sv2v doesn't yet support this feature, but I can add it! I'll update here within a few days.

**Comment by zachjs** [comment]
I've pushed support for enumerated type ranges. Please give it a shot and let me know if it works for you!

Note that `9'hF00` in the above example is rejected by sv2v because the digits make up 12 bits, in excess of the explicitly given width of 9.

**Comment by kauser-rl** [comment]
I seem to have hit an error trying to build from the latest cloned version of the repo. Is it possible to generate a binary for `Ubuntu 20.04`?
