### ISSUE TITLE
Can you create a new stable release version please?

### ISSUE THREAD

**Issue by kauser-rl** [zachjs/sv2v#215]
We are using the tool in our flows and sometimes may need to build from the repo on the fly. It is easier for us to use a stable release tag. However there hasn't been one created since Sept21. We need a critical fix that was made since then, but could benefit from other improvements/checking.
https://github.com/zachjs/sv2v/issues/191

**Comment by zachjs** [comment]
It has been a while since I made a release! Here you go: https://github.com/zachjs/sv2v/releases/tag/v0.0.10
