### ISSUE TITLE
Attributes in expressions

### ISSUE THREAD

**Issue by dwRchyngqxs** [zachjs/sv2v#236]
Hello,
Inside the titan23 benchmark (https://www.eecg.utoronto.ca/~kmurray/titan.html) there is a SystemVerilog file with attributes after a binary operation `ddr_addr_base_init[2] <= ddr_x[1] * (* multstyle = "logic" *) Nb;`.

I am going to try implementing attributes on unary and binary operations unless you don't want them implemented at all.

**Comment by zachjs** [comment]
With your PR merged, I believe this should be resolved. Do you agree?

**Comment by dwRchyngqxs** [comment]
Yes, thank you for your help.
