### ISSUE TITLE
Make test prints a lot of warnings

### ISSUE THREAD

**Issue by dwRchyngqxs** [zachjs/sv2v#241]
Make test prints a lot of warnings about `egrep` being obsolescent and stray `\`:
`grep: warning: stray \ before /`
`egrep: warning: egrep is obsolescent; using grep -E`

**Comment by zachjs** [comment]
I believe I fixed the `grep` warning in 03610606aa1fe919a9e861e2b2e908ffdef43086.
I can't find any explicit reference to `egrep` within this repo. What am I missing?

**Comment by dwRchyngqxs** [comment]
Thank you for the fix. It seems like `egrep` is called by shunit2, I will post an issue there.
