### ISSUE TITLE
LLVM dependency

### ISSUE THREAD

**Issue by jrrk2** [zachjs/sv2v#277]
The README mentions that stack has to be installed, but after installation on homebrew it complains:
Installed GHC.     

<no location info>: error:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM between [9 and 13)

llvm should be mentioned as a dependency for the sake of systems that don't know that. On homebrew OSX 14.2.1 (23C71), version 17.0.6 is installed by default, llvm@13 has to be explicitly specified.

After that happy is happy

**Comment by zachjs** [comment]
Can you share more details (full stack trace, more system details, etc.)?

I'm running the following without issue:
- macOS: 14.3 (23D56)
- Haskell Stack: 2.9.3 x86_64
- llvm: Apple clang version 15.0.0 (clang-1500.1.0.2.5)

**Comment by zachjs** [comment]
@jrrk2 I'm very interested in fixing any issues with the listed dependencies or build instructions. Can you please respond to my comment above? Thank you!

**Comment by zachjs** [comment]
I think this is the same as https://github.com/zachjs/sv2v/issues/280#issuecomment-2054130218. Can you see if the latest version still depends on LLVM?

**Comment by zachjs** [comment]
Based on your reply https://github.com/zachjs/sv2v/issues/280#issuecomment-2056429619, it sounds like the upgraded compiler indeed no longer depends on LLVM when built on Apple Silicon. I believe this issue is now resolved, so I'm closing it. Please reopen if necessary!
