### ISSUE TITLE
Support for `foreach`

### ISSUE THREAD

**Issue by b1f6c1c4** [zachjs/sv2v#33]
A `foreach` loop is more concise than `generate`. It will be very helpful in creating readable code.

**Comment by zachjs** [comment]
Are you suggesting that I add support for parsing and converting `foreach` loops? It's not clear to me how they relate to `generate`.

**Comment by zachjs** [comment]
After #37, this was much easier to implement! I have added support for parsing and converting foreach on master. Please let me know if this fulfills your request.
