### ISSUE TITLE
Spawned from issue #15: uniquify genvars

### ISSUE THREAD

**Issue by NilsGraf** [zachjs/sv2v#46]
This spawned from issue #15: While the implementation for issue #15 works fine, there is a problem when there are multiple generate blocks in a file using the same `genvar i`. In this case, Conformal LEC tool errors out saying that `i` is redefined. 

Could the sv2v tool uniquify all genvars, e.g. by using the name of the generate block, as shown [in example of issue #15](https://github.com/zachjs/sv2v/issues/15#issue-486518474) where `genvar i` becomes `genvar gen_filter_i`?

**Comment by zachjs** [comment]
Thank you for spotting this issue! While my initial fix was different from what you had suggested, I realized that it prevented data declarations declared inside the loop from being referenced as before. This should all now be fixed on master.
