### ISSUE TITLE
Avoid explicit unsigned parameters

### ISSUE THREAD

**Issue by NilsGraf** [zachjs/sv2v#47]
Similar to issue #45, Yosys errors out on the following unsigned parameters:
```
parameter unsigned ...
localparam unsigned ...
```
Could sv2v simply remove the `unsigned` for `parameter` and `localparam`?

Let me know if you need a testcase for this. Thanks!

**Comment by zachjs** [comment]
> Could sv2v simply remove the `unsigned` for `parameter` and `localparam`?

Yes it can, and now it does! Thank you for catching this!
