### ISSUE TITLE
Issue handling always_latch

### ISSUE THREAD

**Issue by nmoroze** [zachjs/sv2v#54]
Hi, thanks for the great work on this tool! I got an unexpected output when converting SystemVerilog code containing an `always_latch` block. I'm not sure if this keyword just isn't supported yet or if it's a proper bug, but here's a code snippet to reproduce - 

Code:
```
module test();
  logic a;
  logic b;
  logic en;
  always_latch begin
    if (en) begin
      a <= b;
    end
  end
endmodule
```

Gives:
```
module test;
	reg a;
	wire b;
	wire en;
	always_latch if (en)
		a <= b;
endmodule
```

Whereas I'd expect something more like this:
```
module test;
  reg a;
  wire b;
  wire en;
  always @(*) begin
    if (en) begin
      a = b;
    end
  end
endmodule
```

**Comment by zachjs** [comment]
Thank you for reporting this issue and providing a test case! This was an oversight on my part. `always_latch` is now converted on master.
