### ISSUE TITLE
Add default git tag so git-describe works

### ISSUE THREAD

**Issue by mithro** [zachjs/sv2v#58]
Could you make and push a tag for your first commit 363ca80af20229a887931f57e2809a876cbf5599?
```
git tag -a v0.0 363ca80af20229a887931f57e2809a876cbf5599 -m "First commit"
git push origin v0.0
```

That way the `git-describe` command will return a useful value for your repository.

**Comment by zachjs** [comment]
Done! Thanks for the heads up!
