### ISSUE TITLE
Support for localparams in parameter list

### ISSUE THREAD

**Issue by dpetrisko** [zachjs/sv2v#7]
foo.v
```
module foo
 #(parameter baz = 2
   , localparam in_width_p = baz + 2
   , localparam out_width_p = baz + 3
   )
  (input [in_width_p-1:0] a
   , output [out_width_p-1:0] b
   );

assign b = a+1;

endmodule
```

Command:
```
$ sv2v --oneunit foo.v
```

Result:
```
sv2v: Parse error: unexpected token 'localparam' (KW_localparam) at ./foo.v:5:6.
CallStack (from HasCallStack):
  error, called at .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/sv2v/sv2v-tmp/Language/SystemVerilog/Parser/Parse.hs:6165:22 in main:Language.SystemVerilog.Parser.Parse
```

I think this feature came in SV-2012
http://www.ece.uah.edu/~gaede/cpe526/2012%20System%20Verilog%20Language%20Reference%20Manual.pdf
Section 06.20.04 
>Local parameters may be declared in a module’s parameter_port_list.

Possibly a solution is to convert localparams in parameter lists to vanilla parameters?

Thanks again!

**Comment by zachjs** [comment]
Thank you for another great report! Support has been added.

**Comment by taylor-bsg** [comment]
Loving these fixes — sv2v is going to be awesome!
